name: Scrape and Clean Real Estate Data

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  scrape-and-clean:
    runs-on: ubuntu-latest
    env:
      WDM_CACHE: ~/.wdm  # ✅ Environment variable added here

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        which chromium-browser
        which chromedriver

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager pandas fake-useragent beautifulsoup4 requests

    - name: Run scraper.py
      run: python scraper.py

    - name: Run cleaner.py
      run: python cleaner.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        if [ -f "raw_data.csv" ]; then
          git add raw_data.csv
        fi
        if [ -f "cleaned_data.csv" ]; then
          git add cleaned_data.csv
        fi
        
        git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
        git commit -m "Automated update: scrape and clean data" || echo "No changes to commit"
        git push origin HEAD:main
